name: patch-nerd-fonts

on:
  pull_request:
    branches:
      - patch-nerd-fonts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Patch Nerd Fonts (Regular)
      run: |
        podman run --rm -v $PWD/SeriousShanns/otf:/in:Z -v $PWD/SeriousShanns/NerdFont:/out:Z nerdfonts/patcher -c
    - name: Patch Nerd Fonts (Mono)
      run: |
        podman run --rm -v $PWD/SeriousShanns/otf:/in:Z -v $PWD/SeriousShanns/NerdFontMono:/out:Z nerdfonts/patcher -c --mono
    - name: Patch Nerd Fonts (Propo)
      run: |
        podman run --rm -v $PWD/SeriousShanns/otf:/in:Z -v $PWD/SeriousShanns/NerdFontPropo:/out:Z nerdfonts/patcher -c --variable-width-glyphs
    - name: Archive files
      run: |
        cd SeriousShanns
        mkdir -p SeriousShanns
        mkdir -p otf
        mkdir -p NerdFont
        mkdir -p NerdFontMono
        mkdir -p NerdFontPropo
        cp -r otf NerdFont NerdFontMono NerdFontPropo SeriousShanns/
        zip -r SeriousShanns.zip SeriousShanns/
        zip -r SeriousShannsOTF.zip otf/
        zip -r SeriousShannsNerdFont.zip NerdFont/
        zip -r SeriousShannsNerdFontMono.zip NerdFontMono/
        zip -r SeriousShannsNerdFontPropo.zip NerdFontPropo/
        rm SeriousShanns/ -r
        cd ..
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Patch Nerd Fonts"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
