name: patch-nerd-fonts

on:
  pull_request:
    branches:
      - patch-nerd-fonts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Patch Nerd Fonts
      run: |
        mkdir -p test
        podman run --rm -v $PWD/SeriousShanns/otf:/in:Z -v $PWD/test:/out:Z nerdfonts/patcher -c
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Add test files"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
